node {
	def app
	stage('Clone repository') {
		/* Lets make sure we have the repository cloned to ou workspace */
		checkout scm
		}
	stage('Build image') {
		/* this builds the actual image; synonymous to 
		* docker build on the command line */

		app  docker.build(getintodevops/hellonode")
		}
	stage('Test image') {
		/*Ideally, we would run a test framework against our image.
		* For this example, were using a volkswagen-type approach ;-) */
		
		app.inside {
			sh 'echo "Testt passed"'
			}
		}
	stage('Push image') {
		/* Finally, well push the image with two tags:
		 * First, the incremental build number rom jenkins
                 * second the latest tag.
		 * Pushing multiple is chap, as all the layers are reused. */
	docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
		app.push("${env.BUILD_NUMBER}")
		app.push("latest")
		}
	}
     }
		
